version: '3.9'
services:
  boda-backend:
    image: registry.pazardev.com/pazardev/boda:1.1.0
    container_name: boda-backend
    env_file: .env
    networks:
      - traefik-proxy
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.boda-backend.rule=Host(`boda-backend.pazardev.com`)
        - traefik.http.routers.boda-backend.service=boda-backend
        - traefik.http.routers.boda-backend.tls=true
        - traefik.http.services.boda-backend.loadbalancer.server.port=80
        - traefik.http.routers.boda-backend.entrypoints=web,websecure
        - traefik.http.routers.boda-backend.tls.certresolver=production
networks:
  traefik-proxy:
    external: true